# Generated by Django 4.0.1 on 2022-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0004_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('currentUser', models.CharField(max_length=255, null=True)),
                ('content', models.TextField()),
                ('date_added', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
