# Generated by Django 4.0.1 on 2022-04-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_rememberlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='universityName',
            field=models.CharField(max_length=101, null=True),
        ),
    ]
