# Generated by Django 4.0.1 on 2022-04-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0011_alter_profile_universityname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='RememberList',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
