# Generated by Django 4.0.1 on 2022-04-08 13:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import friends.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0012_delete_comment_delete_post_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
                ('post_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pics')),
                ('desc', models.TextField(null=True)),
                ('username', models.TextField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('likedby', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=20)),
                ('dislikes', models.IntegerField(default=0)),
                ('dislikedby', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=20)),
                ('postdate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RememberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('friend', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('aboutMe', models.TextField(null=True)),
                ('universityName', models.CharField(max_length=100, null=True)),
                ('startYear', models.IntegerField(null=True)),
                ('endYear', models.IntegerField(null=True)),
                ('educationDesc', models.TextField(null=True)),
                ('interestDesc', models.TextField(null=True)),
                ('interestList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=20)),
                ('friendlist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=20)),
                ('image', models.ImageField(null=True, upload_to=friends.models.path_and_rename)),
                ('banner_image', models.ImageField(null=True, upload_to='pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
